import numpy as np
import torch

from tscls.pipeline.dnn_ae_dd_pipeline import DNNAEDDPipeline
from tscls.pipeline.pipeline_config import (
    PipelineConfig,
    DNNModelConfig,
    AutoencoderConfig,
    StreamConfig,
    OptimizationConfig,
    TrainingConfig,
)
from tscls.simulation.stream_simulation import StreamSimulator


def generate_labels(x: np.ndarray) -> np.ndarray:
    """
    Generate binary labels from a given input array.

    The labels are generated by thresholding the first column of the input array at 0.0.

    Parameters
    ----------
    x : np.ndarray
        The input array.

    Returns
    -------
    np.ndarray
        The generated binary labels.
    """

    return (x[:, 0] > 0.0).astype(np.float32)


def generate_synthetic_data(
    total_samples: int = 900,
    num_features: int = 5,
    seed: int = 42,
):
    """
    Generate synthetic data for concept drift detection experiment.
    The synthetic data are generated by splitting a full synthetic dataset into 3 equal parts.
    The first part is used as reference data, the second part is used as stream data before the drift,
    and the third part is used as stream data after the drift.

    Parameters
    ----------
    total_samples : int, optional
        The total number of samples in the synthetic dataset. Defaults to 900.
    num_features : int, optional
        The number of features in the synthetic dataset. Defaults to 5.
    seed : int, optional
        The seed used for random number generation. Defaults to 42.

    Returns
    -------
    tuple[torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor, int, int]
        A tuple containing the reference samples, reference labels, stream samples, stream labels,
        index at which the drift starts, and the index of the feature that drifts.
    """

    if total_samples % 3 != 0:
        raise ValueError("total_samples must be divisible by 3.")

    rng = np.random.default_rng(seed)
    part_size = total_samples // 3

    # Full synthetic dataset generated from normal distribution
    x_full = rng.normal(
        loc=0.0,
        scale=1.0,
        size=(total_samples, num_features),
    ).astype(np.float32)

    # Labels generated before drift, using a classification task
    y_full = generate_labels(x_full).reshape(-1, 1)

    # Split full synthetic dataset into 3 equal parts
    x_reference = x_full[:part_size].copy()
    y_reference = y_full[:part_size].copy()

    x_stream_before = x_full[part_size:2 * part_size].copy()
    y_stream_before = y_full[part_size:2 * part_size].copy()

    x_stream_after = x_full[2 * part_size:].copy()
    y_stream_after = y_full[2 * part_size:].copy()

    # Choose a random feature for drift
    drift_feature = int(rng.integers(0, num_features))

    # Replace the values of the chosen feature in the post-drift dataset
    # with random numbers between 0 and 1
    x_stream_after[:, drift_feature] = rng.uniform(
        low=0.0,
        high=1.0,
        size=part_size,
    ).astype(np.float32)

    # Build full stream: second third + final third of the 3 equal parts
    x_stream = np.vstack([x_stream_before, x_stream_after]).astype(np.float32)
    y_stream = np.vstack([y_stream_before, y_stream_after]).astype(np.float32)

    # Drift starts at the beginning of the final third
    drift_index = part_size

    return (
        torch.tensor(x_reference, dtype=torch.float32),
        torch.tensor(y_reference, dtype=torch.float32),
        torch.tensor(x_stream, dtype=torch.float32),
        torch.tensor(y_stream, dtype=torch.float32),
        drift_index,
        drift_feature,
    )


def build_config(num_features: int) -> PipelineConfig:
    """
    Build a PipelineConfig object for the DNN + AE drift detection pipeline.

    Parameters
    ----------
    num_features : int
        The number of features in the input data.

    Returns
    -------
    PipelineConfig
        A PipelineConfig object containing the configuration of the pipeline.
    """
    
    return PipelineConfig(
        model=DNNModelConfig(
            input_dim=num_features,
            hidden_dims=[256, 128, 64],
            output_dim=1,
        ),
        autoencoder=AutoencoderConfig(
            input_dim=64,   
            hidden_dim=8,
            threshold_k=3.0,
        ),
        stream=StreamConfig(
            freeze_before_layer=2,
        ),
        optimization=OptimizationConfig(
            base_loss_name="bce_with_logits",
            ae_loss_name="mse",
            stream_loss_name="bce_with_logits",
            base_optimizer_name="sgd",
            ae_optimizer_name="adam",
            stream_optimizer_name="sgd",
            base_learning_rate=1e-2,
            ae_learning_rate=1e-4,
            stream_learning_rate=1e-4,
            gamma1=0.9,
            s1=20,
            gamma2=1.0,
            s2=10,
        ),
        training=TrainingConfig(
            base_epochs=30,
            ae_epochs=10,
        ),
        device="cpu",
    )


def main() -> None:
    """
    Main function to run the synthetic single-drift test.

    This function generates synthetic data, configures the pipeline, runs the pipeline,
    and prints out the results.

    Parameters
    ----------
    None

    Returns
    -------
    None
    """

    num_features = 3

    (
        x_reference,
        y_reference,
        x_stream,
        y_stream,
        drift_index,
        drift_feature,
    ) = generate_synthetic_data(
        total_samples=9999,
        num_features=num_features,
        seed=42,
    )

    stream = StreamSimulator(
        data=x_stream,
        labels=y_stream,
    )

    config = build_config(num_features=num_features)
    pipeline = DNNAEDDPipeline(config=config)

    result = pipeline.run_full_pipeline(
        x_reference=x_reference,
        y_reference=y_reference,
        stream=stream,
    )

    print("Synthetic single-drift test completed")
    print(f"Number of input features: {num_features}")
    print(f"Reference samples: {len(x_reference)}")
    print(f"Stream samples: {len(x_stream)}")
    print(f"Drifted feature index: {drift_feature}")
    print(f"True drift starts at stream index: {drift_index}")
    print(f"Detected drift points (first 20): {result.drift_points[:20]}")
    print(f"Number of detected drift points: {len(result.drift_points)}")
    print(f"First 10 predictions: {[round(p, 4) for p in result.predictions[:10]]}")
    print(
        f"First 10 reconstruction errors: "
        f"{[round(e, 6) for e in result.reconstruction_errors[:10]]}"
    )

    if result.drift_points:
        first_detected = result.drift_points[0]
        print(f"First detected drift point: {first_detected}")
        print(f"Detection delay: {first_detected - drift_index}")
    else:
        print("No drift point detected.")

    print(f"Last 3 Model 1 training losses: {result.base_train_losses[-3:]}")
    print(f"Last 3 autoencoder training losses: {result.ae_train_losses[-3:]}")


if __name__ == "__main__":
    main()